import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen, Button, Field } from '@/src/components/UI';
import colors from '@/constants/colors';
const C = colors.light;

export default function LoginScreen() {
  const [phone, setPhone] = useState<string>('08034567890');
  const [password, setPassword] = useState<string>('password');
  const [hidden, setHidden] = useState<boolean>(true);
  const [loading, setLoading] = useState<boolean>(false);
  const submit = () => { setLoading(true); setTimeout(() => { setLoading(false); router.replace('/(tabs)'); }, 550); };
  return <Screen scroll={false} style={styles.screen}><View style={styles.headerRow}><Pressable onPress={() => router.back()} style={styles.back}><Feather name="arrow-left" size={20} color={C.foreground} /></Pressable><View style={styles.smallBrand}><View style={styles.logo}><Feather name="zap" color="#fff" size={15} /></View><Text style={styles.brandText}>payonce</Text></View><View style={{ width: 40 }} /></View><View style={styles.form}><Text style={styles.kicker}>WELCOME BACK</Text><Text style={styles.title}>Good to see you again.</Text><Text style={styles.subtitle}>Log in to continue managing your payments.</Text><Field label="Phone number or email" value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="0803 456 7890" /><View><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry={hidden} placeholder="Enter your password" /><Pressable style={styles.eye} onPress={() => setHidden((value) => !value)}><Feather name={hidden ? 'eye' : 'eye-off'} size={18} color={C.mutedForeground} /></Pressable></View><Pressable style={styles.forgot}><Text style={styles.link}>Forgot password?</Text></Pressable><Button label="Log in" onPress={submit} loading={loading} /><View style={styles.or}><View style={styles.line} /><Text style={styles.orText}>or</Text><View style={styles.line} /></View><Pressable onPress={() => router.push('/register')} style={styles.create}><Text style={styles.createText}>New to PayOnce? <Text style={styles.link}>Create an account</Text></Text></Pressable></View><Text style={styles.demo}>Demo mode · no real payments are processed</Text></Screen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 24 }, headerRow: { paddingTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 40, height: 40, backgroundColor: C.card, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, smallBrand: { flexDirection: 'row', alignItems: 'center', gap: 8 }, logo: { width: 28, height: 28, borderRadius: 9, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center' }, brandText: { fontFamily: 'Inter_700Bold', color: C.foreground, fontSize: 16 }, form: { marginTop: 74 }, kicker: { color: C.primary, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.5 }, title: { color: C.foreground, fontFamily: 'Inter_700Bold', fontSize: 30, lineHeight: 36, marginTop: 10 }, subtitle: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 22, marginTop: 10, marginBottom: 34 }, eye: { position: 'absolute', right: 16, top: 39, padding: 5 }, forgot: { alignSelf: 'flex-end', marginTop: -4, marginBottom: 24 }, link: { color: C.primary, fontFamily: 'Inter_600SemiBold', fontSize: 13 }, or: { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: 24 }, line: { flex: 1, height: 1, backgroundColor: C.border }, orText: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 12 }, create: { alignItems: 'center', paddingVertical: 10 }, createText: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 13 }, demo: { textAlign: 'center', color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 11, marginBottom: 10 } });