import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Header, Screen } from '@/src/components/UI';
import colors from '@/constants/colors';
const C = colors.light;

export default function ReferralScreen() {
  return <Screen><Header title="Referral" onBack={() => router.back()} /><View style={styles.hero}><View style={styles.gift}><Feather name="gift" size={31} color={C.primary} /></View><Text style={styles.title}>Invite friends and earn</Text><Text style={styles.subtitle}>Give your friends a better way to pay and earn rewards when they join.</Text></View><View style={styles.codeCard}><Text style={styles.codeLabel}>YOUR REFERRAL CODE</Text><View style={styles.codeRow}><Text style={styles.code}>SODIQ123</Text><Pressable onPress={() => Alert.alert('Copied', 'Referral code copied.')}><Feather name="copy" size={18} color={C.primary} /></Pressable></View><View style={styles.divider} /><Text style={styles.codeLabel}>YOUR REFERRAL LINK</Text><Text style={styles.link}>payonce.example/ref/SODIQ123</Text></View><View style={styles.stats}><View><Text style={styles.statValue}>12</Text><Text style={styles.statLabel}>Total referrals</Text></View><View style={styles.statDivider} /><View><Text style={styles.statValue}>8</Text><Text style={styles.statLabel}>Successful</Text></View><View style={styles.statDivider} /><View><Text style={styles.statValue}>₦4,000</Text><Text style={styles.statLabel}>Earnings</Text></View></View><Button label="Share referral" onPress={() => Alert.alert('Share referral', 'Your referral link is ready to share.')} icon="share-2" /><Pressable onPress={() => Alert.alert('Copied', 'Referral code copied.')} style={styles.copyButton}><Text style={styles.copyText}>Copy code</Text></Pressable></Screen>;
}
const styles = StyleSheet.create({ hero: { alignItems: 'center', marginTop: 30 }, gift: { width: 78, height: 78, borderRadius: 28, backgroundColor: C.secondary, alignItems: 'center', justifyContent: 'center' }, title: { color: C.foreground, fontFamily: 'Inter_700Bold', fontSize: 24, marginTop: 20 }, subtitle: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 20, maxWidth: 290, textAlign: 'center', marginTop: 8 }, codeCard: { backgroundColor: C.card, borderRadius: 20, padding: 18, marginTop: 28, borderWidth: 1, borderColor: C.border }, codeLabel: { color: C.mutedForeground, fontFamily: 'Inter_700Bold', fontSize: 9, letterSpacing: 1.1 }, codeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 }, code: { color: C.primary, fontFamily: 'Inter_700Bold', fontSize: 22, letterSpacing: 1.2 }, divider: { height: 1, backgroundColor: C.border, marginVertical: 18 }, link: { color: C.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 13, marginTop: 8 }, stats: { backgroundColor: C.card, borderRadius: 18, marginVertical: 18, padding: 17, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, statValue: { color: C.foreground, fontFamily: 'Inter_700Bold', fontSize: 18, textAlign: 'center' }, statLabel: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 6, textAlign: 'center' }, statDivider: { height: 32, width: 1, backgroundColor: C.border }, copyButton: { alignItems: 'center', paddingVertical: 16 }, copyText: { color: C.primary, fontFamily: 'Inter_600SemiBold', fontSize: 13 } });