import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Header, Screen } from '@/src/components/UI';
import colors from '@/constants/colors';
const C = colors.light;

export default function SecurityScreen() {
  const [biometric, setBiometric] = useState<boolean>(true);
  return <Screen><Header title="Security" onBack={() => router.back()} /><Text style={styles.intro}>Keep your account protected with simple, powerful controls.</Text><View style={styles.card}><Pressable onPress={() => Alert.alert('Change password', 'A secure password reset flow would open here.')} style={styles.row}><View style={styles.icon}><Feather name="lock" size={17} color={C.primary} /></View><View style={styles.copy}><Text style={styles.label}>Change password</Text><Text style={styles.hint}>Last changed 28 days ago</Text></View><Feather name="chevron-right" size={17} color={C.mutedForeground} /></Pressable><Pressable onPress={() => Alert.alert('Transaction PIN', 'A PIN update flow would open here.')} style={styles.row}><View style={styles.icon}><Feather name="key" size={17} color={C.primary} /></View><View style={styles.copy}><Text style={styles.label}>Change transaction PIN</Text><Text style={styles.hint}>Required for payments</Text></View><Feather name="chevron-right" size={17} color={C.mutedForeground} /></Pressable><View style={styles.row}><View style={styles.icon}><Feather name="smartphone" size={17} color={C.primary} /></View><View style={styles.copy}><Text style={styles.label}>Biometric authentication</Text><Text style={styles.hint}>Use Face ID or fingerprint</Text></View><Switch value={biometric} onValueChange={setBiometric} trackColor={{ false: C.border, true: '#A8C1FF' }} thumbColor={biometric ? C.primary : '#fff'} /></View></View><Text style={styles.section}>RECENT LOGIN ACTIVITY</Text><View style={styles.card}><View style={styles.activity}><View style={styles.device}><Feather name="smartphone" size={17} color="#188B62" /></View><View style={styles.copy}><Text style={styles.label}>Android device</Text><Text style={styles.hint}>Lagos, Nigeria · Now</Text></View><View style={styles.current}><View style={styles.liveDot} /><Text style={styles.currentText}>Current</Text></View></View><View style={styles.activity}><View style={styles.device}><Feather name="monitor" size={17} color={C.mutedForeground} /></View><View style={styles.copy}><Text style={styles.label}>Chrome on Windows</Text><Text style={styles.hint}>Lagos, Nigeria · Sep 15</Text></View><Feather name="more-horizontal" size={18} color={C.mutedForeground} /></View></View></Screen>;
}
const styles = StyleSheet.create({ intro: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, marginVertical: 10 }, section: { color: C.mutedForeground, fontFamily: 'Inter_700Bold', letterSpacing: 1.2, fontSize: 10, marginTop: 22, marginBottom: 10 }, card: { backgroundColor: C.card, borderRadius: 19, overflow: 'hidden', borderWidth: 1, borderColor: '#F0F3F7' }, row: { minHeight: 70, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#F0F3F7' }, icon: { width: 35, height: 35, borderRadius: 11, backgroundColor: C.secondary, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, marginLeft: 12 }, label: { color: C.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 13 }, hint: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, activity: { minHeight: 70, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#F0F3F7' }, device: { width: 35, height: 35, borderRadius: 11, backgroundColor: '#EAF8F3', alignItems: 'center', justifyContent: 'center' }, current: { flexDirection: 'row', alignItems: 'center', gap: 5 }, liveDot: { width: 6, height: 6, backgroundColor: '#188B62', borderRadius: 3 }, currentText: { color: '#188B62', fontFamily: 'Inter_600SemiBold', fontSize: 10 } });