import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Field, Header, Screen } from '@/src/components/UI';
import colors from '@/constants/colors';
const C = colors.light;

export default function SupportScreen() {
  const [ticket, setTicket] = useState<boolean>(false);
  const [message, setMessage] = useState<string>('');
  if (ticket) return <Screen><Header title="Contact support" onBack={() => setTicket(false)} /><Text style={styles.title}>How can we help?</Text><Text style={styles.subtitle}>Tell us what went wrong and our team will get back to you.</Text><Field label="Subject" placeholder="What is this about?" /><Field label="Message" placeholder="Describe the issue..." value={message} onChangeText={setMessage} multiline /><Button label="Submit ticket" onPress={() => { setTicket(false); Alert.alert('Ticket submitted', 'We will get back to you shortly.'); }} /></Screen>;
  return <Screen><Header title="Help & support" onBack={() => router.back()} /><Text style={styles.title}>How can we help today?</Text><Text style={styles.subtitle}>Find answers or reach the PayOnce team.</Text><Text style={styles.section}>POPULAR QUESTIONS</Text><View style={styles.card}>{['How do I fund my wallet?', 'Where can I find my receipt?', 'My transaction is pending'].map((question) => <Pressable key={question} style={styles.question} onPress={() => Alert.alert(question, 'This is a demo FAQ answer for the prototype.') }><Text style={styles.questionText}>{question}</Text><Feather name="chevron-down" size={16} color={C.mutedForeground} /></Pressable>)}</View><Text style={styles.section}>CONTACT US</Text><View style={styles.card}><Pressable style={styles.contact} onPress={() => setTicket(true)}><View style={styles.contactIcon}><Feather name="message-circle" size={17} color={C.primary} /></View><View style={styles.copy}><Text style={styles.contactTitle}>Contact support</Text><Text style={styles.contactBody}>Send us a support ticket</Text></View><Feather name="chevron-right" size={17} color={C.mutedForeground} /></Pressable><Pressable style={styles.contact} onPress={() => Alert.alert('WhatsApp support', 'Opening demo WhatsApp support...')}><View style={[styles.contactIcon, { backgroundColor: '#EAF8F3' }]}><Feather name="phone" size={17} color="#188B62" /></View><View style={styles.copy}><Text style={styles.contactTitle}>WhatsApp support</Text><Text style={styles.contactBody}>Usually replies in a few minutes</Text></View><Feather name="external-link" size={16} color={C.mutedForeground} /></Pressable><Pressable style={styles.contact} onPress={() => Alert.alert('Call support', 'Calling demo support line...')}><View style={[styles.contactIcon, { backgroundColor: '#FFF7E8' }]}><Feather name="phone-call" size={17} color="#B4770B" /></View><View style={styles.copy}><Text style={styles.contactTitle}>Call support</Text><Text style={styles.contactBody}>+234 800 000 0000</Text></View><Feather name="external-link" size={16} color={C.mutedForeground} /></Pressable></View></Screen>;
}
const styles = StyleSheet.create({ title: { color: C.foreground, fontFamily: 'Inter_700Bold', fontSize: 24, marginTop: 16 }, subtitle: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 7, marginBottom: 24 }, section: { color: C.mutedForeground, fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.1, marginBottom: 10, marginTop: 8 }, card: { backgroundColor: C.card, borderRadius: 19, overflow: 'hidden', marginBottom: 23, borderWidth: 1, borderColor: '#F0F3F7' }, question: { minHeight: 55, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#F0F3F7' }, questionText: { color: C.foreground, fontFamily: 'Inter_500Medium', fontSize: 13 }, contact: { minHeight: 72, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#F0F3F7' }, contactIcon: { width: 37, height: 37, borderRadius: 12, backgroundColor: C.secondary, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, marginLeft: 12 }, contactTitle: { color: C.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 13 }, contactBody: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 } });