import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Header, Screen, ServiceIcon, Button } from '@/src/components/UI';
import { useApp } from '@/src/context/AppContext';
import { formatNaira } from '@/src/data';
import colors from '@/constants/colors';
const C = colors.light;

export default function TransactionDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { transactions } = useApp();
  const transaction = transactions.find((item) => item.id === id) || transactions[0];
  const statusColor = transaction.status === 'successful' ? '#188B62' : transaction.status === 'pending' ? '#B4770B' : C.destructive;
  return <Screen><Header title="Transaction details" onBack={() => router.back()} /><View style={styles.receipt}><View style={[styles.statusIcon, { backgroundColor: `${statusColor}18` }]}><Feather name={transaction.status === 'successful' ? 'check' : transaction.status === 'pending' ? 'clock' : 'x'} size={24} color={statusColor} /></View><Text style={styles.statusTitle}>{transaction.status === 'successful' ? 'Transaction successful' : transaction.status === 'pending' ? 'Transaction pending' : 'Transaction failed'}</Text><Text style={[styles.statusText, { color: statusColor }]}>{transaction.status}</Text><Text style={styles.amount}>{formatNaira(transaction.amount)}</Text><Text style={styles.reference}>Ref: {transaction.id.toUpperCase()}</Text><View style={styles.divider} /><View style={styles.details}>{[['Service', transaction.service], ['Recipient', transaction.recipient], ['Amount', formatNaira(transaction.amount)], ['Fee', formatNaira(transaction.fee)], ['Total', formatNaira(transaction.amount + transaction.fee)], ['Date', `${transaction.date} · ${transaction.time}`]].map(([label, value]) => <View key={label} style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}</View><View style={styles.receiptFooter}><ServiceIcon type={transaction.icon} size={31} /><Text style={styles.footerText}>Paid with PayOnce wallet</Text></View></View><Button label="Share receipt" onPress={() => Alert.alert('Share receipt', 'Your digital receipt is ready to share.')} variant="secondary" icon="share-2" /><Pressable style={styles.report} onPress={() => Alert.alert('Report a problem', 'A support ticket form would open here.')}><Text style={styles.reportText}>Report a problem</Text></Pressable></Screen>;
}
const styles = StyleSheet.create({ receipt: { backgroundColor: C.card, borderRadius: 24, padding: 21, marginTop: 7, marginBottom: 17, borderWidth: 1, borderColor: C.border }, statusIcon: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, statusTitle: { color: C.foreground, fontFamily: 'Inter_700Bold', textAlign: 'center', fontSize: 18, marginTop: 13 }, statusText: { textTransform: 'capitalize', fontFamily: 'Inter_600SemiBold', textAlign: 'center', fontSize: 11, marginTop: 5 }, amount: { color: C.foreground, fontFamily: 'Inter_700Bold', textAlign: 'center', fontSize: 29, marginTop: 20 }, reference: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', textAlign: 'center', fontSize: 11, marginTop: 6 }, divider: { borderStyle: 'dashed', borderWidth: 1, borderColor: C.border, marginVertical: 22 }, details: { gap: 15 }, row: { flexDirection: 'row', justifyContent: 'space-between' }, label: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 12 }, value: { color: C.foreground, fontFamily: 'Inter_600SemiBold', fontSize: 12, maxWidth: 190, textAlign: 'right' }, receiptFooter: { borderTopWidth: 1, borderTopColor: C.border, marginTop: 22, paddingTop: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, footerText: { color: C.mutedForeground, fontFamily: 'Inter_500Medium', fontSize: 11 }, report: { alignItems: 'center', paddingVertical: 16 }, reportText: { color: C.destructive, fontFamily: 'Inter_600SemiBold', fontSize: 13 } });