import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen, Header } from '@/src/components/UI';
import colors from '@/constants/colors';
const C = colors.light;
const menu = [
  { label: 'Personal information', icon: 'user', route: '/support' },
  { label: 'Security', icon: 'shield', route: '/security' },
  { label: 'Transaction PIN', icon: 'key', route: '/security' },
  { label: 'Notifications', icon: 'bell', route: '/notifications' },
  { label: 'Referral', icon: 'gift', route: '/referral' },
  { label: 'Help & support', icon: 'help-circle', route: '/support' },
];

export default function ProfileScreen() {
  return <Screen style={styles.screen}><Header title="Profile" right={<Pressable style={styles.settings} onPress={() => router.push('/security')}><Feather name="settings" size={18} color={C.foreground} /></Pressable>} /><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>AS</Text></View><View><Text style={styles.name}>Abdulazeez Sodiq</Text><Text style={styles.muted}>0803 456 7890</Text><Text style={styles.muted}>sodiq@example.com</Text></View><Pressable style={styles.edit}><Feather name="edit-2" size={15} color={C.primary} /></Pressable></View><Text style={styles.sectionLabel}>ACCOUNT</Text><View style={styles.menu}>{menu.map((item) => <Pressable key={item.label} onPress={() => router.push(item.route as never)} style={styles.menuItem}><View style={styles.menuIcon}><Feather name={item.icon as keyof typeof Feather.glyphMap} size={17} color={C.primary} /></View><Text style={styles.menuLabel}>{item.label}</Text><Feather name="chevron-right" size={17} color={C.mutedForeground} /></Pressable>)}</View><Text style={styles.sectionLabel}>MORE</Text><View style={styles.menu}><Pressable style={styles.menuItem}><View style={[styles.menuIcon, { backgroundColor: '#FFF0F1' }]}><Feather name="file-text" size={17} color={C.destructive} /></View><Text style={styles.menuLabel}>Terms & conditions</Text><Feather name="chevron-right" size={17} color={C.mutedForeground} /></Pressable><Pressable style={styles.menuItem}><View style={[styles.menuIcon, { backgroundColor: '#FFF0F1' }]}><Feather name="lock" size={17} color={C.destructive} /></View><Text style={styles.menuLabel}>Privacy policy</Text><Feather name="chevron-right" size={17} color={C.mutedForeground} /></Pressable></View><Pressable style={styles.logout} onPress={() => router.replace('/login')}><Feather name="log-out" size={17} color={C.destructive} /><Text style={styles.logoutText}>Log out</Text></Pressable><Text style={styles.version}>PayOnce v1.0.0 · Prototype</Text></Screen>;
}
const styles = StyleSheet.create({ screen: { paddingHorizontal: 20 }, settings: { width: 42, height: 42, borderRadius: 14, backgroundColor: C.card, alignItems: 'center', justifyContent: 'center' }, profileCard: { padding: 17, backgroundColor: C.card, borderRadius: 20, flexDirection: 'row', alignItems: 'center', marginBottom: 25, borderWidth: 1, borderColor: '#F0F3F7' }, avatar: { width: 58, height: 58, borderRadius: 20, backgroundColor: C.secondary, alignItems: 'center', justifyContent: 'center', marginRight: 14 }, avatarText: { color: C.primary, fontFamily: 'Inter_700Bold', fontSize: 16 }, name: { color: C.foreground, fontFamily: 'Inter_700Bold', fontSize: 15, marginBottom: 5 }, muted: { color: C.mutedForeground, fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 2 }, edit: { marginLeft: 'auto', width: 32, height: 32, borderRadius: 11, backgroundColor: C.secondary, alignItems: 'center', justifyContent: 'center' }, sectionLabel: { color: C.mutedForeground, fontFamily: 'Inter_700Bold', letterSpacing: 1.2, fontSize: 10, marginBottom: 10, marginLeft: 4 }, menu: { backgroundColor: C.card, borderRadius: 19, marginBottom: 22, overflow: 'hidden', borderWidth: 1, borderColor: '#F0F3F7' }, menuItem: { minHeight: 59, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, borderBottomColor: '#F0F3F7', borderBottomWidth: 1 }, menuIcon: { width: 34, height: 34, borderRadius: 11, backgroundColor: C.secondary, alignItems: 'center', justifyContent: 'center', marginRight: 12 }, menuLabel: { flex: 1, color: C.foreground, fontFamily: 'Inter_500Medium', fontSize: 13 }, logout: { height: 52, borderRadius: 16, backgroundColor: '#FFF0F1', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 }, logoutText: { color: C.destructive, fontFamily: 'Inter_600SemiBold', fontSize: 14 }, version: { textAlign: 'center', color: C.mutedForeground, fontSize: 10, marginTop: 18, fontFamily: 'Inter_400Regular' } });